### PR TITLE
MNT: Re-rendered with conda-build 3.20.3, conda-smithy 3.8.0, and con…

### PR DESCRIPTION
**Pull request by jwillemsen**
…da-forge-pinning 2020.10.07.09.03.27

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jwillemsen** [comment]
@conda-forge-admin, please rerender

**Review by traversaro — APPROVED** [review]

**Comment by wolfv** [comment]
@jwillemsen thanks for all your work here and also on conda-smithy and the rest of the ecosystem! Do you have other recipes that you would like to have on conda-forge? I am happy to help out!

**Comment by jwillemsen** [comment]
Not at this moment, depends on the needs of our users like @traversaro

**Comment by traversaro** [comment]
I personally only needed ace as it is a dependency of YARP, that we extensively use on the iCub robot. At the moment I am still trying in my free time to get our software to compile with conda-forge dependencies (see https://github.com/robotology/robotology-superbuild/issues/477) and after that I have some ideas on how to even have conda binaries for those, but let's do one thing at the time. The extremely nice thing that I noticed is that we have a lot of commonalities with the work that you (@wolfv and @Tobias-Fischer) are doing in https://github.com/RoboStack, so I should drop a line in RoboStack's Gitter one of these days.

**Comment by Tobias-Fischer** [comment]
Yes that is very true. I think it would be great to have a robotology-superbuild like thing on conda. From my memory it shouldn't be too bad to build yarp and icub-main now that ACE is built. Drop by on gitter and maybe send me a private message there, too - it would be great to get your opinion on something.

**Pull request merged**
