### PR TITLE
Add linking tests and fix macOS rpath

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jwillemsen** [comment]
Maybe use mpc to generate the build files, see the ace examples

**Comment by traversaro** [comment]
> Maybe use mpc to generate the build files, see the ace examples

I was trying to simulate the downstream users of the ACE library, for this reason I prefer to have full control (and understanding) of what the compiler is doing, as I imagine that at least some downstream uses of ACE (at least the one in YARP) do not use mpc. Indeed I was able to replicate the problem, as now the example works fine on Linux and Windows, while it fails on macOS.

**Comment by traversaro** [comment]
After a few trial and errors, I was able to fix the problem. The main problem is that the rpath option given in https://github.com/DOCGroup/ACE_TAO/blob/25f5307a46b10ebe7f26f46c006892f0e249c365/ACE/include/makeinclude/platform_macosx_yosemite.GNU#L6 specify that the install location of the library is `@rpath/$@`, where `$@` is the name of the Make target. The problem is that the name of the target is `64/libACE.dylib`, so the installed name is also expected to inside a `64` directory, that in practice does not exist. For this reason I substituted in  `$@` with `$(notdir $@)` that get just the file name out of the target name, i.e. only `libACE.dylib`.

**Comment by jwillemsen** [comment]
Isn’t the ‘64’ directory set through a specific environment variable which you could use?

**Comment by traversaro** [comment]
> 
> 
> Isn’t the ‘64’ directory set through a specific environment variable which you could use?

This is a good question, for which I don't have an answer. Unfortunately the MPC/Makefile-based build system of ACE is not completely clear to me, so it is not clear how the target names are computed.

**Comment by jwillemsen** [comment]
I don’t have a mac anymore so I can’t try this, maybe you can make an issue upstream for this issue in ACE, maybe someone else with a mac can try this

**Review by jwillemsen — APPROVED** [review]

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
> 
> 
> I don’t have a mac anymore so I can’t try this, maybe you can make an issue upstream for this issue in ACE, maybe someone else with a mac can try this

Ok! By the way, I tried to understand why everything was working on Homebrew (the only other package manager on which we use) and I guess there homebrew does something after the build of binaries, such as removing rpath that are pointing to non-existing directories, but this is just my guess.

**Pull request merged**
