### PR TITLE
ACE 6.5.20

### PR DESCRIPTION
**Pull request by jwillemsen**
* recipe/meta.yaml:

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jwillemsen** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
I would change `conda-forge.yml` last lines from:
~~~
provider:
  linux_aarch64: default
  linux_ppc64le: default
~~~

to 
~~~
build_platform:
  linux_aarch64: linux_aarch64
  linux_ppc64le: linux_ppc64le
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
~~~

and re-render, so that we just build in Azure that is much more reliable then Travis and CircleCi .

**Comment by jwillemsen** [comment]
@conda-forge-admin, please rerender

**Comment by jwillemsen** [comment]
> I would change `conda-forge.yml` last lines from:
> 
> ```
> provider:
>   linux_aarch64: default
>   linux_ppc64le: default
> ```
> 
> to
> 
> ```
> build_platform:
>   linux_aarch64: linux_aarch64
>   linux_ppc64le: linux_ppc64le
> provider:
>   linux_aarch64: azure
>   linux_ppc64le: azure
> ```
> 
> and re-render, so that we just build in Azure that is much more reliable then Travis and CircleCi .

Make that change also on main?

**Comment by jwillemsen** [comment]
@traversaro Ok to merge?

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
> @traversaro Ok to merge?

Ok for me!

**Pull request merged**
